### ISSUE TITLE
ERROR Unexpected token <:

### ISSUE THREAD

**Issue by veqlargh** [argnist/Cliche#13]
When I start Cliche I get this ERROR message. I can't even create an album.

Cliche: 1.1.0 RC1
MODX Revolution 2.2.9-pl

ERROR MESSAGE:

Unexpected token <:
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, webmaster@mywebsite.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by argnist** [comment]
Could you reproduce this error in http://modx-test.com/?lang=en ?

**Comment by veqlargh** [comment]
No, I can't reproduce this error. All I did is downloaded cliche via package manager and installed it. Than when I opened it I got this error. I have tried delteting it and reinstall but I got the same error.
Could it be server error?

**Comment by argnist** [comment]
May be. I used it on some sites and there is no error.
