### ISSUE TITLE
AlbumSelect not working 

### ISSUE THREAD

**Issue by yuka123** [argnist/Cliche#4]
PHP message: PHP Parse error:  syntax error, unexpected '[' in /var/www/cef/core/components/cliche/elements/tv/input/clichealbumselect.class.php on line 11" 

And it gives internal error in manager when opening any resource that has the new TV assigned. 

Could you check this?

**Comment by argnist** [comment]
Version of MODX and PHP?

**Comment by argnist** [comment]
If PHP < 5.4 try to replace in /var/www/cef/core/components/cliche/elements/tv/input/clichealbumselect.class.php
$this->setPlaceholder('action',$this->modx->request->getActionIDs(array('index'), 'cliche')['index']); 
by:
$action = $this->modx->request->getActionIDs(array('index'), 'cliche');
$this->setPlaceholder('action',$action['index']);
Probably it's PHP version difference http://stackoverflow.com/questions/742764/php-syntax-for-dereferencing-function-result
If it helps I will update package soon,

**Comment by yuka123** [comment]
Yeh it should be php version problem , it's  5.3.10, But you as dev need to take that in account. Many people are still using less then 5.4 , thanks for help, tough gonna try fixing it.

**Comment by yuka123** [comment]
Confirmed this fixed the error. 

Question tough, is it possible with this, to add an Album to resource but choose only few photos from that Album not whole album for example?

**Comment by argnist** [comment]
I've just updated package without new version number.
