### ISSUE TITLE
Album Navigation

### ISSUE THREAD

**Issue by greyskymedia** [argnist/Cliche#5]
It'd be great to get some album navigation. Just next and previous.

**Comment by argnist** [comment]
What do you mean?

**Comment by greyskymedia** [comment]
While in an album, have a next and previous button so users can navigate between albums

Jamison Mergens
916.234.0040

On Jun 13, 2013, at 12:35 AM, argnist notifications@github.com wrote:

What do you mean?

**Comment by argnist** [comment]
I think it is easier to navigate to the album through album list. Your suggestion is interesting but not clear to me.
